using System.IO;
using UnityEditor;
using UnityEngine;

public class SceneEnumGenerator : MonoBehaviour
{
    [SerializeField]
    private const string _directory = "Assets/00. Core/00-20. Util";
    private const string _enumFilePath = _directory + "/ESceneNames.cs";

    [MenuItem("Tools/Generate Scene Enum")]
    public static void GenerateSceneEnum()
    {
        if (!Directory.Exists(_directory))
        {
            Directory.CreateDirectory(_directory);
        }

        EditorBuildSettingsScene[] scenes = EditorBuildSettings.scenes;

        using (StreamWriter writer = new StreamWriter(_enumFilePath))
        {
            writer.WriteLine("// Auto-generated by SceneEnumGenerator");
            writer.WriteLine("public enum ESceneNames");
            writer.WriteLine("{");

            foreach (var scene in scenes)
            {
                if (!scene.enabled) continue;

                string path = scene.path;
                string sceneName = Path.GetFileNameWithoutExtension(path);
                sceneName = sceneName.Replace(" ", "_");

                writer.WriteLine($"    {sceneName},");
            }

            writer.WriteLine("}");
        }

        AssetDatabase.Refresh();
    }
}