using System.IO;
using UnityEditor;
using UnityEngine;

public class TagEnumGenerator : MonoBehaviour
{
    [SerializeField]
    private const string _directory = "Assets/00. Core/00-20. Util";
    private const string _tagEnumFilePath = _directory + "/ETags.cs";

    [MenuItem("Tools/Generate Tag Enum")]
    public static void GenerateTagEnum()
    {
        if (!Directory.Exists(_directory))
        {
            Directory.CreateDirectory(_directory);
        }
        string[] tags = UnityEditorInternal.InternalEditorUtility.tags;
        using (StreamWriter writer = new StreamWriter(_tagEnumFilePath))
        {
            writer.WriteLine("// Auto-generated by TagEnumGenerator");
            writer.WriteLine("public enum ETags");
            writer.WriteLine("{");

            foreach (string tag in tags)
            {
                writer.WriteLine($"{tag.Replace(" ", "_")},");
            }

            writer.WriteLine("}");
        }
        AssetDatabase.Refresh();
    }
}
