public enum EStatType 
{ 
    MoveSpeed,
    Health,
    MaxHealth,
    Damage,
    AttackSpeed,
    SprintSpeed,
    MaxStamina,
    CurrentStamina,
    SprintStaminaUseRate,
    TargetDashStaminaUseRate,
    StaminaRegenRate,
    MaxAmmo,
    CurrentAmmo,
    ReloadInterval,
    ExplodeRange,
    Count
}